### PR TITLE
Restore undefined newThing

### LINKED ISSUE #106: Cannot Add Address, Email or Phone to Profile
When editing my dev.inrupt.net Profile, I cannot add a new Address, Email, or Phone.

## To Replicate
1. Log into a dev.inrupt.net Pod.
2. "Edit your profile".
3. Click on green + next to Address, Email, or Phones.

## Expected Behaviour
1. A new Address, Email, or Phone is added to the Profile.

## Actual Behaviour
1. Nothing visible happens.
2. In Console, an error is displayed:
``forms.js:194 Uncaught TypeError: r.newThing is not a function
    at HTMLTableRowElement._ (forms.js:194)``

### PR DESCRIPTION
**Pull request by Vinnl**
Note that it is also present in `buttons`, but since it was just
two lines and does not appear to be related specifically to
buttons, I went with just duplicating the code for forms.

It was broken initially by f618510e95d139fceeb0bbda9e85c50239160090, in which `newThing` was
moved to buttons but not to forms.

Fixes #106.

(Basically the same reason b7589cd394751c126718b360e5a1eeb9a46bfcbd was needed.)

### CODE REVIEW

**Comment by Vinnl** [comment]
Whoops, apparently already done in 47fcb334f8894efdce84fe12627ee2df78f3d1cf.
